name:  OneBlockChallenge
main:  ru.OBC.Main.Main
version:  latest
api-version: 1.16
authors: [itzHiti, Lairon]
commands:
  config:
    usage: /config
    description: Основные команды для JSON-текстов.
    aliases: [conf]
  obc:
    usage: /obc
    description: Просто чтобы релоадить плагин.
    aliases: [oneblackchallenge]
